export type Language = {
  language: string;
  languageSlug: string;
  countries: string;
  speakerCount: string;
  dialectNote: string;
  languageFAQ: string;
};

export const languages: Language[] = [
  {
    language: "Spanish",
    languageSlug: "spanish",
    countries: "Spain, Mexico, Colombia, Argentina, and 17 more countries",
    speakerCount: "500 million",
    dialectNote: "Supports Latin American Spanish and Castilian Spanish",
    languageFAQ: "Does Captio work with Mexican Spanish and Latin American accents?",
  },
  {
    language: "French",
    languageSlug: "french",
    countries: "France, Belgium, Switzerland, Canada, and 25 more countries",
    speakerCount: "310 million",
    dialectNote: "Supports Standard French, Canadian French, and Belgian French",
    languageFAQ: "Does Captio work with Québécois French accent?",
  },
  {
    language: "German",
    languageSlug: "german",
    countries: "Germany, Austria, Switzerland",
    speakerCount: "135 million",
    dialectNote: "Supports Standard German, Austrian and Swiss German",
    languageFAQ: "Does Captio work in Swiss German dialect?",
  },
  {
    language: "Italian",
    languageSlug: "italian",
    countries: "Italy, Switzerland, San Marino",
    speakerCount: "85 million",
    dialectNote: "Supports Standard Italian and regional accents",
    languageFAQ: "Does Captio work with Southern Italian accents?",
  },
  {
    language: "Portuguese",
    languageSlug: "portuguese",
    countries: "Brazil, Portugal, Angola, Mozambique",
    speakerCount: "260 million",
    dialectNote: "Supports Brazilian Portuguese and European Portuguese",
    languageFAQ: "Does Captio distinguish between Brazilian and European Portuguese?",
  },
  {
    language: "Dutch",
    languageSlug: "dutch",
    countries: "Netherlands, Belgium",
    speakerCount: "25 million",
    dialectNote: "Supports Standard Dutch and Flemish Dutch",
    languageFAQ: "Does Captio work with Belgian Dutch (Flemish)?",
  },
  {
    language: "Russian",
    languageSlug: "russian",
    countries: "Russia, Belarus, Kazakhstan, Kyrgyzstan",
    speakerCount: "258 million",
    dialectNote: "Supports Standard Russian across all regional accents",
    languageFAQ: "Does Captio work with regional Russian accents?",
  },
  {
    language: "Japanese",
    languageSlug: "japanese",
    countries: "Japan",
    speakerCount: "125 million",
    dialectNote: "Supports Standard Japanese (Tokyo dialect) and common regional speech",
    languageFAQ: "Does Captio work with Osaka dialect (Kansai-ben)?",
  },
  {
    language: "Korean",
    languageSlug: "korean",
    countries: "South Korea, North Korea",
    speakerCount: "80 million",
    dialectNote: "Supports Standard Korean (Seoul dialect)",
    languageFAQ: "Does Captio work for Korean sign language users who also speak Korean?",
  },
  {
    language: "Chinese",
    languageSlug: "chinese",
    countries: "China, Taiwan, Singapore",
    speakerCount: "1.1 billion",
    dialectNote: "Supports Mandarin (Simplified and Traditional characters)",
    languageFAQ: "Does Captio support Cantonese as well as Mandarin?",
  },
  {
    language: "Arabic",
    languageSlug: "arabic",
    countries: "Egypt, Saudi Arabia, UAE, Morocco, and 18 more countries",
    speakerCount: "420 million",
    dialectNote: "Supports Modern Standard Arabic and major regional dialects",
    languageFAQ: "Does Captio work with Egyptian Arabic and Gulf Arabic dialects?",
  },
  {
    language: "Hindi",
    languageSlug: "hindi",
    countries: "India",
    speakerCount: "600 million",
    dialectNote: "Supports Standard Hindi and common regional accents",
    languageFAQ: "Does Captio work with Hinglish (Hindi-English code-switching)?",
  },
  {
    language: "Turkish",
    languageSlug: "turkish",
    countries: "Turkey, Cyprus",
    speakerCount: "88 million",
    dialectNote: "Supports Standard Turkish across all regional accents",
    languageFAQ: "Does Captio work for deaf people who use Turkish Sign Language?",
  },
  {
    language: "Polish",
    languageSlug: "polish",
    countries: "Poland",
    speakerCount: "45 million",
    dialectNote: "Supports Standard Polish and regional accents",
    languageFAQ: "Does Captio work with Silesian or Kashubian accents in Polish?",
  },
  {
    language: "Swedish",
    languageSlug: "swedish",
    countries: "Sweden, Finland",
    speakerCount: "13 million",
    dialectNote: "Supports Standard Swedish and Finland Swedish",
    languageFAQ: "Does Captio work with Swedish regional dialects like Scanian?",
  },
  {
    language: "Norwegian",
    languageSlug: "norwegian",
    countries: "Norway",
    speakerCount: "5 million",
    dialectNote: "Supports Bokmål and Nynorsk varieties of Norwegian",
    languageFAQ: "Does Captio support both Bokmål and Nynorsk Norwegian?",
  },
  {
    language: "Danish",
    languageSlug: "danish",
    countries: "Denmark",
    speakerCount: "6 million",
    dialectNote: "Supports Standard Danish",
    languageFAQ: "Does Captio work with Danish regional accents?",
  },
  {
    language: "Finnish",
    languageSlug: "finnish",
    countries: "Finland",
    speakerCount: "5 million",
    dialectNote: "Supports Standard Finnish",
    languageFAQ: "Does Captio work for Finnish deaf community users?",
  },
  {
    language: "Greek",
    languageSlug: "greek",
    countries: "Greece, Cyprus",
    speakerCount: "13 million",
    dialectNote: "Supports Standard Modern Greek",
    languageFAQ: "Does Captio work with Cypriot Greek accent?",
  },
  {
    language: "Ukrainian",
    languageSlug: "ukrainian",
    countries: "Ukraine",
    speakerCount: "40 million",
    dialectNote: "Supports Standard Ukrainian",
    languageFAQ: "Does Captio work for Ukrainian deaf and hard of hearing users?",
  },
  {
    language: "Czech",
    languageSlug: "czech",
    countries: "Czech Republic",
    speakerCount: "11 million",
    dialectNote: "Supports Standard Czech",
    languageFAQ: "Does Captio work with Czech regional accents and dialects?",
  },
  {
    language: "Romanian",
    languageSlug: "romanian",
    countries: "Romania, Moldova",
    speakerCount: "24 million",
    dialectNote: "Supports Standard Romanian",
    languageFAQ: "Does Captio work for Romanian hard of hearing users?",
  },
  {
    language: "Hungarian",
    languageSlug: "hungarian",
    countries: "Hungary, Romania, Slovakia",
    speakerCount: "13 million",
    dialectNote: "Supports Standard Hungarian",
    languageFAQ: "Does Captio work for Hungarian deaf community users?",
  },
  {
    language: "Thai",
    languageSlug: "thai",
    countries: "Thailand",
    speakerCount: "60 million",
    dialectNote: "Supports Standard Thai (Central Thai dialect)",
    languageFAQ: "Does Captio work with Thai regional dialects and tones?",
  },
  {
    language: "Vietnamese",
    languageSlug: "vietnamese",
    countries: "Vietnam",
    speakerCount: "95 million",
    dialectNote: "Supports Northern and Southern Vietnamese varieties",
    languageFAQ: "Does Captio work with both Northern (Hanoi) and Southern (Ho Chi Minh City) Vietnamese?",
  },
  {
    language: "Indonesian",
    languageSlug: "indonesian",
    countries: "Indonesia",
    speakerCount: "270 million",
    dialectNote: "Supports Standard Indonesian (Bahasa Indonesia)",
    languageFAQ: "Does Captio work with Indonesian regional accents?",
  },
  {
    language: "Malay",
    languageSlug: "malay",
    countries: "Malaysia, Singapore, Brunei",
    speakerCount: "33 million",
    dialectNote: "Supports Standard Malay and Malaysian English-Malay speech",
    languageFAQ: "Does Captio work with Bahasa Malaysia and Singaporean Malay?",
  },
  {
    language: "Hebrew",
    languageSlug: "hebrew",
    countries: "Israel",
    speakerCount: "9 million",
    dialectNote: "Supports Modern Hebrew",
    languageFAQ: "Does Captio work for Israeli deaf and hard of hearing users?",
  },
  {
    language: "Catalan",
    languageSlug: "catalan",
    countries: "Spain (Catalonia, Valencia, Balearic Islands), Andorra",
    speakerCount: "10 million",
    dialectNote: "Supports Central Catalan and Valencian",
    languageFAQ: "Does Captio work with Valencian dialect of Catalan?",
  },
];

export function getLanguageBySlug(slug: string): Language | undefined {
  return languages.find((l) => l.languageSlug === slug);
}
